# Generated by Django 5.0 on 2024-01-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='BrandModel',
        ),
    ]
